#application.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - app:  dev-app
            cluster: in-cluster
            path: prod
            revision: HEAD
            namespace: dev
            repo: argo-applicationset
          - app: uat-app
            cluster: docker-desktop
            path: prod
            revision: main
            namespace: monitoring
            repo: argo-applicationset
  template:
    metadata:
      name: '{{app}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Tykama/{{repo}}.git
        targetRevision: '{{revision}}'
        path: '{{path}}'
      destination:
        name: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true